name: Pipeline

on: [pull_request]

env:
  QT_VERSION:   "6.2.0"
  MSVC_VERSION: "win64_msvc2019_64"

jobs:
  build-and-test:
    runs-on: windows-latest
    name: Build and Test
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ env.QT_VERSION }}
        host: "windows"
        target: "desktop"
        arch: ${{ env.MSVC_VERSION }}
        dir: "${{ github.workspace }}/qt"
        install-deps: "true"

    - name: Qt Setup
      run: |
        echo "${{ github.workspace }}/qt/Qt/${{ env.QT_VERSION }}/${{ env.MINGW_PATH }}/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        refreshenv

    - name: GUI Unit Tests
      run: |
        mkdir -p build
        cd build
        qmake ../tests/guitests.pro
