name: Pipeline

on: [pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest
    name: Formatting

    container:
      image: campbellbrown/formatting:0.1
      options: --user 1001

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Format C++
      run: |
        python3 scripts/format_cpp.py
        git diff --exit-code

  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test

    container:
      image: fstlx/qt5:ubuntu18

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir -p tmpbuild
        cd tmpbuild
        qmake ../src/TaskApp.pro
        make -j $(nproc)

    - name: Unit Tests
      run: |
        apt-get install -y xvfb
        mkdir -p tmptest
        cd tmptest
        qmake ../tests/tests.pro
        make -j $(nproc)
        find . -type f -executable | xargs -I % sh -c '{ xvfb-run % || exit 1; sleep 1; }'

    - name: GUI Unit Tests
      run: |
        apt-get install -y xvfb
        mkdir -p tmpguitest
        cd tmpguitest
        qmake ../tests/guitests.pro
        make -j $(nproc)
        find . -type f -executable | xargs -I % sh -c '{ xvfb-run % || exit 1; sleep 1; }'
