name: Pipeline

on: [pull_request]

jobs:
  build-and-test:
    runs-on: windows-latest
    name: Build and Test
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: "5.15.2"
        host: "windows"
        target: "desktop"
        arch: "win64_msvc2019_64"
        dir: "${{github.workspace}}/qt"
        install-deps: "true"

    - name: GUI Unit Tests
      run: |
        mkdir -p build
        cd build
        qmake ../tests/guitests.pro
