name: Pipeline

on: [pull_request]

env:
  QT_VERSION:   "6.2.0"
  MSVC_VERSION: "win64_msvc2019_64"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test

    container:
      image: fstlx/qt5:ubuntu18
      options: --user 1001

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: GUI Unit Tests
      run: |
        apt-get install -y xvfb
        mkdir -p build
        cd build
        qmake ../tests/guitests.pro
        make -j $(nproc)
        find . -type f -executable | xargs -I % sh -c '{ xvfb-run % || exit 1; sleep 1; }'
